version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - $PWD/init/db:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - $PWD/data/db:/var/lib/mysql # I want to manage volumes manually.

  php:
#    image: wodby/wordpress:4-7.2-3.3.1
    image: wodby/wordpress:4-7.1-3.3.1
    environment:
      WP_ENV: development
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
    volumes:
      - $PWD/config/php/php.ini:/usr/local/etc/php/php.ini
      - $PWD/www:/var/www/html
#      - $PWD/data/bin/build.sh:/usr/local/bin/build.sh
#    command: /bin/ash -c "/usr/local/bin/build.sh"

  nginx:
    image: wodby/wordpress-nginx:4-1.13-3.0.2
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
    volumes:
      - $PWD/www:/var/www/html
    depends_on:
      - php
    labels:
      - 'traefik.backend=<project-name>_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:<project-name>.docker.localhost'
#      - 'traefik.frontend.rule=HostRegexp:{subdomain:.+}.<project-name>.docker.localhost,<project-name>.docker.localhost'

#  varnish:
#    image: wodby/wordpress-varnish:4.1-2.3.1
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=<project-name>_varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.<project-name>.docker.localhost'

#  redis:
#    image: wodby/redis:4.0-2.1.4

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=<project-name>_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.<project-name>.docker.localhost'

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:2.10.0
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=<project-name>_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.<project-name>.docker.localhost'

#  portainer:
#    image: portainer/portainer
#    command: --no-auth -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - 'traefik.backend=<project-name>_portainer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:portainer.<project-name>.docker.localhost'
